### ISSUE TITLE
Authorizations status update

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-android#12]
**Summary:**  
`We need to adjust the statuses of the each authorization, so that customer has clear understanding of what is going on with authorization, after the "Allow"/"Deny" action.`

**Design:** https://www.figma.com/file/rHX6WxGERgdCezvpOHtOhr/Figma---Auth-Android-V2?node-id=0%3A1  

**Task:**  
State 1: "Authorizations" page, when app is just opened;  
State 2: "Authorization" page, when app is opened via push-notification.

The difference between UI in "Authorizations" vs "Authorization" pages is that "Authorizations" page has "Tab bar" in the bottom of screen, and there is an extra step - confirmation with Fingerprint/Passcode.
- [x] 1) Screen 1: After what customer pressed on either "Allow" or "Deny", the whole authorization should freeze, authorization becomes "in progress" and app is waiting for the final status. While "in progress" -  background is blurred, the "spinner" is displayed, "Authorizing..." title and description "Please wait while authorization is processing" are shown.
- [x] 2) Screen 2: If customer pressed "Allow", successful status is shown when action was successfully processed by Service Provider. Once "Allowed", background is still blurred, the "spinner" is changed to icon with "check-mark", title should be "Success" and description: "Your action was successfully authorized".
- [x] 3) Screen 3: If customer pressed "Deny", deny status is shown when action was successfully processed by Service Provider. Once "Denied", background is still blurred, the "spinner" is changed to icon with "minus" sign, title should be "Denied" and description: "Your action was denied".
- [x] 4) Screen 4: If customer pressed either "Allow" or "Deny" and process was NOT processed by Service Provider, meaning that we've received an error, then: background is still blurred, the "spinner" is changed to red icon with "exclamation mark" sign, title should be "Something went wrong" and description: "Please try again".
- [x] 5) Screen 5: If customer DID NOT press either "Allow" or "Deny", the process is finished for Service Provider, the whole authorization should freeze and background is blurred, the "time out" icon is displayed, together with "Time out" title and description "Time to authorize the action is out".

Additionally:
- [x] 6) When the final state of authorization is available, it should automatically close in 3 seconds for State 1, and app should automatically close for state 2.
- [x] 7) "Authorization unavailable" message should be displayed if customer reacted on authorization from State 1, and then opened the push-notification and app could not find necessary authorization.

**Logic behind the authorizations list:**  
- We will use LILO approach - Last In > Last Out, taking into consideration already existing in list authorizations.
- When authorization gets to the list, it holds a position, for example, we have 5 authorizations from 2 providers that came in from polling when we opened application, namely "1.1", "1.2", "1.3", "2.1", "2.2". When in next 2 seconds we refresh the list, they can come into different, chaotic order, like: "1.2", "1.3", "1.1", "2.2", "2.1". The list should not renew it's order, just update the content, in case there are any changes. Logic should verify whether there are new authorizations and put them in the end of the list. In case while getting updated list of authorizations from polling, the app cannot find an authorization from the list that is displayed to customer, then the missing authorization just disappears.
To cover all cases, for example we already have in list the following authorizations: "1.1", "1.2", "1.3", "2.1", "2.2". Now, user has confirmed authorization "1.1", authorization "2.1" was confirmed in another app, and there are 2 new incoming authorizations from polling. As a result we have new incoming list, namely: "2.2", "2.3", "1.4", "1.3", "1.2", "3.1", so the final list will look for customer as following: "1.2", "1.3", "2.2", "2.3", "1.4", "3.1".

**Screenshot**  
When app is just opened (State 1):  
![image](https://user-images.githubusercontent.com/38658558/64434349-0a38a880-d0c9-11e9-97bb-d6a4da297069.png)

When app is opened via push notification (State 2):  
![image](https://user-images.githubusercontent.com/38658558/64434381-191f5b00-d0c9-11e9-9cf2-6ba952641694.png)

Authorization unavailable:  
![image](https://user-images.githubusercontent.com/38658558/64425511-8ffe2900-d0b4-11e9-9562-f60253d2261d.png)

**Comment by AlexLobaciov** [comment]
@ConstantinKV you can proceed

**Comment by AlexLobaciov** [comment]
@ConstantinKV @mnewlive 3 flows to implement and keep in mind:
- 1) Push notification tap > Open expanded authorization, but on polling there is no that specific authorization > show status "Authorization Unavailable"
- 2) Push notification tap > Open expanded authorization > User taps on "Allow" or "Deny" > error from service provide > show status "Something went wrong"
- 3) Push notification tap > Open expanded authorization > meanwhile, someone either allows the action from another device, or bank rejects the authorization for some reason > show status "Authorization Unavailable"
