### ISSUE TITLE
Design (UX/UI) upgrade for the "Connections" page

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-android#15]
**Summary:**  
`The "Connections" page requires some small adjustments to have a great user experience`

**Materials:**  
Figma design file: https://www.figma.com/file/rHX6WxGERgdCezvpOHtOhr/Auth-V2---Android?node-id=0%3A1

**Task:**  
*Screen 1:*
- [x] Rename title to `No Connections`
- [x] Rename description to "You have no currently connected service providers. Connect one to start receiving authorizations for your actions (e.g. payments)."

*Screen 2:*
- [x] "Trash bin" icon should be eliminated
- [x] The Service Provider icon should fit the gray "background circle"
Just verify here that all proportions are met on "Connections" tab

*Screen 3:*
- [x] Once user presses "Delete" button, a pop-up window shows up. Header should be named "Delete connection", and description is "You will stop receiving authorization requests from provider. Are you sure you want to delete this connection?". Please adjust.
- [x] Change the buttons to blue color, and please name buttons "CANCEL" and "SUBMIT".

*Screen 4,5:*
- [x] Rename all options so they don't have word "Connection". Make them as in design.

*Screen 6:*
All good here

*Screen 7:*  
- [x] New button to add in "Settings" - "Clear all data". Button is red, in 3rd - separate block in settings. Please verify design. The functionality will clean service providers as well as cache. The app should be clean, but PIN is left. After what user presses on "Clear all data" button, a confirmation step with Title "Delete all data?", description "All app data including service providers, user data and settings will be permanently deleted." and blue buttons "CANCEL" and "SUBMIT" is present. After what user presses "Submit" - all data is cleared and user gets to the clean "Connections" page.

**Screenshots:**  
![image](https://user-images.githubusercontent.com/38658558/64693129-412f0580-d49f-11e9-98ee-1e91b9e53879.png)

*Clear all data* screen:  
![image](https://user-images.githubusercontent.com/38658558/64853983-4a49df00-d625-11e9-8125-cc3f29709a35.png)

___
Thanks!

**Comment by AlexLobaciov** [comment]
@ConstantinKV @mnewlive you can proceed

**Comment by mnewlive** [comment]
@AlexLobaciov Please add additions that are associated with data deletion.

**Comment by AlexLobaciov** [comment]
> @AlexLobaciov Please add additions that are associated with data deletion.

Description updated. Please proceed.

**Comment by ConstantinKV** [comment]
@AlexLobaciov @mnewlive submit button should be replaced with "OK" text

**Comment by AlexLobaciov** [comment]
@mnewlive  
1) Please adjust the Service Provider logo to fit the 48x48 placeholder. Please remove the grey background,  just make it fit the round icon.
2) The "Clear all data" button should not delete the Passcode and other on-boarding setup. So, when I kill app and enter the app I should just open app with Passcode/Fingerprint.

Thanks!

**Comment by AlexLobaciov** [comment]
@mnewlive
1. Please eliminate the line after last item in block
2. Apply the #D6D6D6 color as "grey-light"
3. Adjust the distance between the first item and Tool bar on "Connections" and "Settings" pages to be the same (20px according to the design)
4. Apply block style in "Settings" to the connections on "Connections" page

**Comment by AlexLobaciov** [comment]
Looks awesome! Thanks!
