### ISSUE TITLE
Adjust the process of establishing new "connection"

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-android#16]
**Summary:**  
`On each step of adding new Service Provider (creating new "connection"), all the processes should be clear for user` 

**Materials:**  
Figma design file: https://www.figma.com/file/rHX6WxGERgdCezvpOHtOhr/Auth-V2---Android?node-id=0%3A1

**Task:**  
*Screen 1:*  
- [x] "<-" (back) icon should be replaced with "x" icon, as we cancel the action and don't go "back"

*Screen 2:*  
While connection is in progress:
- [x] "<-" (back) icon should be replaced with "x" icon, as we cancel the action and don't go "back". Keep it for next 2 screens
- [x] Action bar title should be "New connection". Keep it for next 2 screens (when user is reconnecting, please use "Reconnect" title in action bar).
- [x] Spinner should be placed on top of action screen
- [x] Title to be added, named "Connecting..."
- [x] Description to be added, named "This may take some time. Please wait."

*Screen 3:*  
While user is in WebView, just keep the action bar same as previous

*Screen 4:*  
While user has successfully connected new Service Provider, please keep the action bar same as previous, and:
- [x] Description should be renamed to "Your Service Provider has been successfully connected to the Authenticator App. You will receive an authorization request every time you make an action."

**Screenshots (if applicable)**  
![image](https://user-images.githubusercontent.com/38658558/64353962-3f7cc200-d007-11e9-82a3-43c6103522ca.png)

**Comment by AlexLobaciov** [comment]
Looks good! Thanks!
