### ISSUE TITLE
Settings and "Change passcode" adjustment

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-android#17]
**Summary:**  
`Clear and convenient Settings to be in final product`

**Materials:**  
Figma design file: https://www.figma.com/file/rHX6WxGERgdCezvpOHtOhr/Auth-V2---Android?node-id=0%3A1

**Task:**  
- [x] Update settings page
Settings should have following structure:
- Block 1: Passcode
- Block 1: Notificaitons
- Block 1: Screenshot lock
- Block 2: About
- Block 2: Report a bug
Please adjust as in design.

- [x] Rename "Change Passcode" to "Passcode"
- [x] Rename "Here you can.." to "Change passcode"
- [x] Rename "Input current Passcode" to "Input current passcode"
- [x] Rename "Input New Passcode" to "Input new passcode"
- [x] Rename "Repeat New Passcode" to "Repeat new passcode"

**Screenshots (if applicable)**  
![image](https://user-images.githubusercontent.com/38658558/64032968-3053cb00-cb54-11e9-839d-c98864012046.png)

**Comment by AlexLobaciov** [comment]
@mnewlive  
1) the blocks have shadow instead of simple line (under the block). Please adjust.
2) "switch" buttons have wrong colors for "enabled" state. Please double check colors for the "disabled" state.

Thanks!

**Comment by AlexLobaciov** [comment]
@mnewlive  
1. Please eliminate the line after last item in block
2. Apply the #D6D6D6 color as "grey-light"
3. Adjust the distance between the first item and Tool bar on "Connections" and "Settings" pages to be the same (20px according to the design)
4. Apply block style in "Settings" to the connections on "Connections" page
