### ISSUE TITLE
Dark mode update for Android 10+

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-android#187]
**Summary:**  
Starting with Android 10, the system by default supports the dark mode. Hence, there is an opportunity to enable dark mode automatically for the app when it is licked to the system settings.

**Task:**  
1.  For the Android OS 10+, please add the new option is Settings: "System dark mode". By default it is enabled. If user taps on "Moon" icon, then this option disables automatically - and user control the mode manually. Once user enables it back - the app should verify the current mode of the system and activate the correct mode.
2.  For the Android OS 9 and below, please keep the same logic. By default app got light mode, and user can only switch to dark mode - manually. User preference is kept in this case.
3.  Additionally, for the Settings, please add the distance for the option "Clear all data" (distance to add below the option "Report an issue")

**Screenshots (if applicable)**  

![image](https://user-images.githubusercontent.com/38658558/85016924-53974780-b173-11ea-9913-7cbc679330cf.png)

**Comment by AlexLobaciov** [comment]
@mnewlive 

- [ ] 1) App on Dark mode, system on Light mode. After I tap the toggle to enable "System dark mode" - app locks. Can it be switched without lock?
- [ ] 2) App on Light mode, system on Light mode. I switch (tap on "Moon") to enable Dark mode. At this moment the "system dark mode" should automatically disable.
- [ ] 3) App on Dark mode, system on Light mode. After I tap the toggle to enable "System dark mode" - app locks and after unlock - I want to switch to app Dark mode, and tap on "Moon" icon. On the first step - nothing happens.
- [ ] 4) Toggle icon colors are correct only in "disabled" state. Please adjust color of toggle (switcher) in both - Light and Dark Mode.
 
<details>
  <summary><b>Screenshots:</b></summary>

![image](https://user-images.githubusercontent.com/38658558/86910227-0844d900-c122-11ea-9ea4-7c41070471c6.png)

![image](https://user-images.githubusercontent.com/38658558/86910298-26123e00-c122-11ea-862c-73fac0d8de7e.png)

![image](https://user-images.githubusercontent.com/38658558/86910306-2a3e5b80-c122-11ea-9abf-e8496e085fe9.png)


</details>

**Comment by AlexLobaciov** [comment]
All LIVE, thanks!
