### ISSUE TITLE
Geolocation & Authorization info collection

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-android#271]
**Summary:**  
Reference issue: https://github.com/saltedge/sca-identity-service-example/issues/55

**Task:**  
- [ ] 1) On application setup - ask user for permission to collect his GPS data. 
<details>
  <summary><i>Example</i></summary>
![image](https://user-images.githubusercontent.com/38658558/109417378-19519b80-79cc-11eb-92f8-6df263f67fbf.png)
</details>

- [ ] 2) If user denies the permission
- [ ] Update SDK accordingly.

**Comment by baller784** [comment]
1. In the Connection response, should be parsed a new field - isGeolocationRequired.

- `isGeolocationRequired` **[bool, optional]**
 
  Add a new optional Bool field `isGeolocationRequired` in the Connection model.

2. After the successful Connection enrolment, check the received `isGeolocationRequired` field:
- If `isGeoloctionRequired` is nil, skip this step.
- If `isGeoloctionRequired` is true, **and sharing of the geolocation isn’t already enabled**, the mobile app should ask for the permission for Geolocation usage.
- If `isGeolocationRequired` is false, skip this step.

3. When a mobile application receives the Authorisation, check whether this provider requires the geolocation. Access the Authorisation’s connection, by the `connectionId`, which is already in the authorisation response.

4. Authorisation flow:
- If `isGeolocationRequired` true, and geolocation sharing is enabled, allow user to make an action
- If `isGeolocationRequired` is true and the user has declined the geolocation permission, hide the action buttons(Confirm/deny) and replace buttons with the following text: “Your service provider requires your GPS data to authorize action. To continue, please allow using the geolocation in your phone settings”.
- If `isGeolocationRequired` false allow user to make an action
- If `isGeolocationRequired` is nil allow user to make an action

5. Add `GEO-Location` header. Geolocation will be shared with SCA service as a HTTP Header in the next format:

	`GEO-Location` [string, optional]
	Format using [RFC2426], i.e. `GEO:<latitude>;<longitude>`

	Example:
 	GEO-Location:  “GEO:52.506931;13.144558”

6. By confirming/denying the Authorisation the HTTP request should contain the geolocation header. Retrieve the user’s geolocation using the mobile location api and make the request.

**Comment by baller784** [comment]
**Point 3. User authorization type.**

We should send the type of how user has been authenticated in the app, using `biometrics` or `passcode`. To do this, would be a better choice to create a global variable somewhere in the app, which will store the authentication type.

Example:
`var userAuthorizationType = "biometrics"`

The `userAuthorizationType` should be send, when confirming/denying the authorization, as an HTTP header in the following format:

`Authorization-Type` **[string, required]**

Example:
`"Authorization-Type": "biometrics"`

Backend could ignore extra headers, that's why we can send the `Authorization-Type` with every request.

**Comment by AlexLobaciov** [comment]
@ConstantinKV

Please consider the following flows with issues to be fixed:
- [ ] User creates connection (enrollment) > as a result app is asking for permission to "Allow access to location while using the app", which is perfectly fine, but if I tap on "DENY", the application never asks me again about granting permission for using geolocation. With value "true" from provider, user MUST provide location per each authorization request. Hence, the next time, when user has authorization request to be confirmed, it is necessary to ask user again to grant permission for geolocation.
- [ ] With condition if `isGeoloctionRequired` is `true`, it is also required for Android app to require "enabling" the GPS (Location) functionality. In most cases, user's location feature is turned off. Now, after what permission is granted, but functionality "location" is turned off, the Identity Service does not get the location info. Hence, each time, when user has authorization request to be confirmed, it is necessary to ask user to enable "location" service. See example below.

I suggest using following message:   
- Title: "Enable GPS"
- Description: "Please enable GPS. Your service provider is requesting your location for accurate risk analysis."
- Buttons: "CANCEL" & "ENABLE"

![image](https://user-images.githubusercontent.com/38658558/118268266-d9c42700-b4c5-11eb-8337-a5a5d9780615.png)

The "ENABLE" button takes user to the respective "Location" feature in Settings menu, where he can turn on GPS.

Example:

![image](https://user-images.githubusercontent.com/38658558/118268460-14c65a80-b4c6-11eb-81cf-9c1edca2abaf.png)

**Comment by AlexLobaciov** [comment]
@mnewlive 

Please review the update in the issue description.

**Comment by ConstantinKV** [comment]
@mnewlive take a look to this articles 
https://www.codeproject.com/Questions/613512/How-to-start-GPS-ON-and-OFF-programatically-in-And  
https://stackoverflow.com/questions/4721449/how-can-i-enable-or-disable-the-gps-programmatically-on-android

**Comment by AlexLobaciov** [comment]
@mnewlive 

- [ ] 1) Please try to realize the following point, since there are such implementations in other app: "Button "ENABLE" should turn on the GPS service directly", without sending user to Location Settings.
- [ ] 2) If access is not granted, the connection menu has point "Access to Locations" in 2 rows, please rename to "Access to location" and fit in single row
- [ ] 3) As discussed, please update the "marker" icon in connections menu

**Comment by AlexLobaciov** [comment]
@mnewlive 

Point 2 - "2) "Enable GPS" (turn on location service) when provider sets geolocation data as mandatory" - not necessary to do, as discussed

New logic:
- [ ] 1) If Location ON and permission granted > location data taken from GPS
- [ ] 2) If Location OFF and permission granted > location data taken from network

Thanks!
