### ISSUE TITLE
App setup improvement

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-android#35]
**Summary:**  
`UX and styles improvement`  

**Design:** https://www.figma.com/file/rHX6WxGERgdCezvpOHtOhr/Figma---Auth-Android-V2?node-id=0%3A1  

**Task:**  
- [x] Screen 1: For "Getting started" - join the icon, title and description in 1 block. This block should be in the middle in regards to the Status bar and Page controls.
- [x] Screen 2: For "App setup" - please keep the Title + Description place in regards to the progress line, but the Icon should be centered, so it's always in the center on the screen.
- [x] Screen 2: On "Well done!" screen, please leave button "Proceed" - the same size and on the same level as previous button (e.g. "Allow notifications"). There should be no automatic switch to "Connections" page. Please update the description text to "Application has been successfully set. Proceed to connect your service provider."

**Screenshots:**  
![image](https://user-images.githubusercontent.com/38658558/65584640-dd6e0780-df89-11e9-8e1a-f40ecc5e0589.png)

![image](https://user-images.githubusercontent.com/38658558/65584726-ff678a00-df89-11e9-934e-128d1ba86ca7.png)

**Comment by AlexLobaciov** [comment]
Looks nice! Thanks!
