### ISSUE TITLE
Design (UX/UI) upgrade for the "Authorizations" page

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-android#4]
**Summary:**  
`In the application, we cannot conveniently use TextView (enriched text) as it is quite messy when displaying the HTML. "Authorizations" page was completely reviewed and new design was proposed to cover all possible situations. Hence, it is required to update design of the "Authorizations" page in both situations - with many "authorizations" available (swiping), and full screen authorization (when page is accessed from push-notification)`

**Actual behavior:**  
`TextView does not display the HTML styles properly on "Authorizations" page (as does the WebView) and this causes breach in the universality of the app` 

**Expected behavior:**  
`Design (UI/UX) should be updated according to the confirmed prototype`

**Materials:**  
*Prototype*  
https://projects.invisionapp.com/prototype/authentication-animation-cjyzm398p004nqn010nrwcgsf/play/053c9162  
*Figma files*  
https://www.figma.com/file/fFkej9m0LqBKhlnHSYhejv/New-Auth-Screens?node-id=1%3A912  
https://www.figma.com/file/rHX6WxGERgdCezvpOHtOhr/Auth-V2---Android?node-id=0%3A1

**Task:**    
Remove TextView completely and keep WebView with new design for both states of the "Authorizations" page.  
- [x] 1) Adjust expanded "Authorization" page (accessible from push notification)
- [x] 2) Adjust simple "Authorizations" page with multiple `authorizations` available for confirmation (reached when user just opens the app)
- [x] 3) In "empty" state (no authorizations), please rename the description to "You have no active authorizations. Once an action authorization is generated, it will be valid for a few minutes."
- [x] 4) Remove the "refresh" button in top left corner please - it is unnecessary. as we refresh the content every 2 seconds.

**Screenshots:**  
When app is opened:  
![image](https://user-images.githubusercontent.com/38658558/64354109-79e65f00-d007-11e9-8891-b51d391616f9.png)

When push notification is opened:  
![image](https://user-images.githubusercontent.com/38658558/64354152-8b2f6b80-d007-11e9-9496-e27da0cf0700.png)

Empty state:  
![image](https://user-images.githubusercontent.com/38658558/64354221-adc18480-d007-11e9-8d24-6c243e4db40f.png)

___
Thanks!

**Comment by AlexLobaciov** [comment]
Looks awesome! Thanks!
