### ISSUE TITLE
Instant action implementation

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-android#81]
**Summary:**  
With introduced “Instant action” the app should have additional logic to proceed with user authentication, select the necessary provider and catch the redirect deep link.

Related issue: https://github.com/saltedge/sca-identity-service-example/issues/8

**Task:**
- [x] Screen 1,2:  Add a “QR code” icon - button to tap and scan QR code for “instant action”. Button should be added on top right corner of the “Authorizations” page.
- [x] Screen 3: In case there are 2 similar connected accounts, the app will have to ask user which exactly account to choose. Please add the "Choose connection" page after what QR code is scanned and app does not know which connection to choose.
- [x] Screen 4: Add a new processing window with loading spinner and title “Authenticating for action”, with description "This may take some time. Please wait.".
- [x] Screen 5,6: If SCA is NOT required for specific action = the app should show final status with title “Successful action” and description “Action was successfully processed". If flow ends up with an error - final status should be “Action error” and description “Please try again”  
- [x] If SCA IS required then from loading screen (screen 3) user should get directly to the “Authorization request” screen (full authorization screen).  
- [x] Realize the API endpoint to make a signed POST request to transmit to the Identity Service by the “is_url” the “action_id” and “access_token”.
- [x] Receive in response to the previous action the result “OK”/”Error”, and if successful, then to proceed with the received “authorization_id”.
- [x] If user scans QR code and app could not find the service provider, app should show error "Provider not found. Please create connection to your service provider and try again.".
- [x] Implement return to action caller, feature. 

**Design:**  
https://www.figma.com/file/APPwTTmJsiSn02CbisDmEW/Autheticator-Android?node-id=346%3A1071

![image](https://user-images.githubusercontent.com/38658558/74140275-7762e380-4bfd-11ea-82df-6836ff9bf2f5.png)

**Comment by mnewlive** [comment]
@AlexLobaciov now task is in the block status.

**Comment by mnewlive** [comment]
> We tried connecting your Provider to the Authenticator App, but something went wrong. Please try again or contact our Support Team!

Replaced on:

> Provider not found. Please create connection to your service provider and try again.

Discussed with @AlexLobaciov

**Comment by mnewlive** [comment]
@AlexLobaciov  please provide all necessary string resources.

**Comment by AlexLobaciov** [comment]
> @AlexLobaciov please provide all necessary string resources.

Design, screens and strings in issue are updated. Please proceed.

**Comment by AlexLobaciov** [comment]
@mnewlive 

- [ ] "Choose connections" page name change to "Choose connection"
- [ ] Please update the design and names according to the issue details and design. Flow works good so far.
