### ISSUE TITLE
Additional parameters to add to each server request

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-android#90]
**Summary:**  
For every request that Salt Edge Authenticator performs to the server, it is necessary to additionally provide some important information for the Audit log.

**Task:**  
- [x] Add the User agent request header for all REST requests
- [x] Add the User agent request header for WebView requests
- [x] Update documentation and examples.

header should contains: application name, application version, application installer package name

**Comment by ConstantinKV** [comment]
good example https://github.com/danielceinos/Cooper/blob/master/cooper/src/main/java/com/danielceinos/cooper/CooperInterceptor.kt

**Comment by ConstantinKV** [comment]
example for WebView: ```myWebView.getSettings().setUserAgentString("Android")```
